spring:
  cache:
    cache-names: balance,curs,operation
    caffeine:
      spec: maximumSize=500,expireAfterAccess=120s
  sql:
    init:
      mode: always
  boot:
    admin:
      client:
        url: http://localhost:8080
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdemo
    username: postgres
    password: 556677
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


