spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdemo
    username: postgres
    password:


  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

